spring:
  application:
    name: devmobile
  datasource:
    url: ${PG_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${PG_DB_USERNAME:admin}
    password: ${PG_DB_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

server:
  servlet:
    context-path: /api/v1